services:
  mongodb:
    image: mongo:latest
    ports:
      - 27017:27017
    container_name: mongodb
    volumes:
      - mongodb-data:/data/db
    networks:
      - app-network
  server:
    build:
      context: ./server
      target: development
    ports:
      - 4000:4000
    container_name: server
    depends_on:
      - mongodb
    networks:
      - app-network
  client:
    build: ./
    ports:
      - 3000:3000
    container_name: client
    depends_on:
      - server
    networks:
      - app-network
volumes:
  mongodb-data:

networks:
  app-network: